version: '3'
services:
    mongodb:
      image: mongo:5.0.2
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - 7017:27017
      volumes:
        - db:/data/db
    app:
      depends_on:
        - mongodb
        - kafka
      build: ./server
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - 6868:8000
      stdin_open: true
      tty: true

    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 22181:2181

    kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
        - mongodb
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db:
    driver: local
