version: '3'
services:
    mongodb:
      image: mongo:5.0.2
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - $MOGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
      volumes:
        - db:/data/db
    app:
      depends_on:
        - mongodb
      build: ./server
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      stdin_open: true
      tty: true

volumes:
  db:
    driver: local
