version: '3'
services:
    mongodb:
      image: mongo:5.0.2
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - 7017:27017
      volumes:
        - db:/data/db
    app:
      depends_on:
        - mongodb
      build: ./server
      restart: unless-stopped
      env_file: ./server/.env
      ports:
        - 6868:8000
      stdin_open: true
      tty: true

volumes:
  db:
    driver: local
