express:
  port: 8080
  debug: 5858
  host: means-api

auth:
  jwt_secret: "UR4swimlane$"

mongo:
  urlClient: "mongodb://127.0.0.1:27017/means-api"
  urlDocker: "mongodb://mongo:27017/means-api"

# none/debug/info
loglevel: info
