name: Futbol-Means Server CI
on:
  push:
    branches:
      - main

    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yaml'

jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm install

      - name: Analyze Syntax
        run: npx gulp lint

      - name: Run tests
        run: npx gulp test

#      - name: Report Coverage
#        uses: coverallsapp/github-action@master
#        with:
#          flag-name: "Futbol-Means Server"
#          path-to-lcov: "./server/coverage/lcov.info"
#          github-token: ${{ secrets.github_token }}

