name: Futbol-Means Server CI
on:
  push:
    branches:
      - main

    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yaml'

jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Report Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

      - name: Run lint
        run: npm run lint
